# this doesn't work
# {% set data = load_setup_py_data() %}

package:
  name: {{ environ.get('CONDA_PKG') }}
  version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
  number: {{ environ.get('CONDA_PKG_BUILD') }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
    - numpy
  run:
    - python
    - numpy

about:
  home: "https://github.com/epi2me-labs/ncbitaxonomy"
  license: GPL3
  license_file: LICENSE.md
  summary: "Cut down version of ETE3 ncbi_taxonomy for epi2melabs."
  doc_url: https://github.com/epi2me-labs/ncbitaxonomy
  dev_url: https://github.com/epi2me-labs/ncbitaxonomy

extra:
  recipe-maintainers:
    - cjw85

